export const GET_DRAWING_REQUEST = "GET_DRAWING_REQUEST";
export const GET_DRAWING_SUCCESS = "GET_DRAWING_SUCCESS";
export const GET_DRAWING_FAILURE = "GET_DRAWING_FAILURE";

export const UPDATE_VIEW_VISIBILITY_REQUEST = "UPDATE_VIEW_VISIBILITY_REQUEST";
export const UPDATE_VIEW_VISIBILITY_SUCCESS = "UPDATE_VIEW_VISIBILITY_SUCCESS";
export const UPDATE_VIEW_VISIBILITY_FAILURE = "UPDATE_VIEW_VISIBILITY_FAILURE";

export const GET_TRB_MODEL_REQUEST = "GET_TRB_MODEL_REQUEST";
export const GET_TRB_MODEL_SUCCESS = "GET_TRB_MODEL_SUCCESS";
export const GET_TRB_MODEL_FAILURE = "GET_TRB_MODEL_FAILURE";